#!/bin/bash

# Author: Matthias Maderer
# E-Mail: edvler@edvler-blog.de
# URL: https://github.com/edvler/check_mk-btrfs_health
# License: GPLv2

export LC_ALL=C

mounts_btrfs=""
devices_btrfs="$(awk '/ btrfs / { print $1 }' < /proc/mounts | sort | uniq)"

for dev in $devices_btrfs; do
    mounts_btrfs="${mounts_btrfs} "$(awk "\$1 == \"${dev}\" { print \$2; }" < /proc/mounts)
done

mounts_btrfs=${mounts_btrfs# }

test -z $mounts_btrfs && exit

echo "<<<btrfs_health_dstats>>>"
btrfs --version
for vol in $mounts_btrfs
do
    btrfs device stats $vol | awk -v vol="$vol" '{print "stats::" vol " " $0}'
done


echo "<<<btrfs_health_usage>>>"
btrfs --version
for vol in $mounts_btrfs
do
    btrfs filesystem usage --raw $vol | awk -v vol="$vol" '{print "usage::" vol " " $0}'
done


echo "<<<btrfs_health_scrub>>>"
btrfs --version
for vol in $mounts_btrfs
do
    btrfs scrub status $vol | awk -v vol="$vol" '{print "scrub::" vol " " $0}'
done
